### ISSUE TITLE
Support OkHttp 4

### ISSUE THREAD

**Issue by 4brunu** [rightek/square.okhttp#1]
Hey, 
As today, the last version of OkHttp is [4.2.2](https://github.com/square/okhttp/releases/tag/parent-4.2.2)
Could you please add support for OkHttp 4.X?
Thanks

**Comment by dehghani-mehdi** [comment]
Hi,

[OkHttp v4.x is same as v3.x. the only different is v4.x use Kotlin](https://square.github.io/okhttp/upgrading_to_okhttp_4/). so I think there is no need to create binding for v4.x. also the main library for Xamarin developers is [Picasso](https://github.com/rightek/square.picasso), and Picasso depends on OkHttp. upgrading OkHttp may broke Picasso.

**Comment by 4brunu** [comment]
Hi,

Ok, for me this issue can be closed.

**Comment by dehghani-mehdi** [comment]
@4brunu if you using `OkHttp` for making http request in your app, I think it's not a good idea, I was there, you should use `System.Net.Http.HttpClient`.

_p.s: You can use our wrapper, [RHttp](https://github.com/rightek/rhttp)_
